### PR TITLE
update build gradle files

### PR DESCRIPTION
**Pull request by dkanada**
@thornbill you can test this to see if the build is fixed.

Closes #32

### CODE REVIEW

**Comment by dkanada** [comment]
@thornbill alright what about this version?

**Comment by JustAMan** [comment]
@dkanada @grafixeyehero Does this supersede #32?

**Comment by dkanada** [comment]
@grafixeyehero this PR should fix your issues and still build for @thornbill, if you are still having issues try disabling instant run on Android Studio. Please let me know if this PR fixes your build problems.

@JustAMan this PR does negate the other PR assuming it solves everyones issues.

**Comment by JustAMan** [comment]
@dkanada can you include @grafixeyehero to contributors, seeing that your PR consumed theirs (but theirs was made earlier)?

**Comment by joshuaboniface** [comment]
Closes #32

**Pull request merged**
