### PR TITLE
Add RTL Support

### PR DESCRIPTION
**Pull request by hadicharara**
**Changes**
I added RTL support for this app. Most of the work was clicking the refactor button in Android Studio. Other parts included properly formatting numbers (to support Eastern Arabic Numbers, for example), rewriting certain layouts (like legacy card image layout) and adding more constraints to others.

**Issues**
None

### CODE REVIEW

**Comment by hadicharara** [comment]
I am open to any feedback!

**Comment by nielsvanvelzen** [comment]
Sorry for the wait. I'm currently busy preparing the 0.14 release and this PR might break some things so it will be added for 0.15 to give us some more time to test it. From a quick glance it looks fine but I'll properly review it in the coming weeks.

**Comment by hadicharara** [comment]
No worries mate. Take your time.

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
Changes look fine for the most part but the changes in the view_card_legacy_image layout cause the card shadows to enable in the browsing view, which shouldn't happen:

image

**Comment by hadicharara** [comment]
I'm looking into it.

**Comment by hadicharara** [comment]
It's weird as I don't get the same result:
image
Did you do anything in particular to see those rectangular opaque shadows?

**Comment by nielsvanvelzen** [comment]
It only showed in the browsing screen (so when in a library)

**Comment by hadicharara** [comment]
I couldn't reproduce it. I am guessing maybe it has to do with your non-stock theme. Should I just eliminate shadows going down?

**Comment by hadicharara** [comment]
Also are we sure these are shadows?

**Comment by nielsvanvelzen** [comment]
> I am guessing maybe it has to do with your non-stock theme.

It's the default theme

> Also are we sure these are shadows?

Partially background, partially shadow

**Comment by hadicharara** [comment]
I meant your OS theme. The title progress bar and the tick don't look the same on my machine. Honestly, I couldn't reproduce it so I don't know what to do.

**Comment by nielsvanvelzen** [comment]
Testing was done with the Android emulator (Android 12) with nothing changed.

**Comment by hadicharara** [comment]
I tried both Android 12 TV emulator images available in Android Studio. Neither look like your screenshot. They looked more like mine. There was a light blue circle tick and no shadow. I'm sorry, I couldn't reproduce the issue. I don't know what to do.

**Comment by nielsvanvelzen** [comment]
Did some more testing and apparently this only happens when the library is set to align items vertically, weirdly enough.

**Comment by hadicharara** [comment]
Thank you! I managed to reproduce it! I'll investigate the root cause.

**Comment by hadicharara** [comment]
It should be fixed now.

**Review by nielsvanvelzen — APPROVED** [review]
Seems to work now! Thanks!

**Pull request merged**
