### PR TITLE
New overlay: code cleanup, fixes and general enhancements

### LINKED ISSUE #340: Duration not updated when next item is played
When finishing the current video and the next item starts playing (eg. when watching a series) the duration is not updated.
Im working on a fix already.

### PR DESCRIPTION
**Pull request by Florianisme**
Fixes #340

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I'm assuming you plan to add more commits to this PR and mark it as "ready for review" when you're done?

First commit looks good btw

**Comment by Florianisme** [comment]
Yes exactly!

**Comment by thornbill** [comment]
Hey @Florianisme, any further updates here?

**Comment by nielsvanvelzen** [comment]
@Florianisme I'm going to merge this PR for now as the current changes are good. Additional changes can be added in a new PR. Thanks for your contributions! :)

**Pull request merged**
