### PR TITLE
Fix NPE when autologin is disabled

### PR DESCRIPTION
**Pull request by MrChip53**
**Changes**
Move the restore session call to onCreate in StartupActivity to fix the race condition.

**Issues**

### CODE REVIEW

**Comment by MrChip53** [comment]
@nielsvanvelzen I'm honestly not sure if moving away from the generic lifecycle event and into the specific activity has any ill effects so if you would like a different implementation

**Comment by MrChip53** [comment]
Unused import I left in again. Damn auto import on copy/paste lol

**Comment by nielsvanvelzen** [comment]
This PR effectively reverts an important part of #1082 so in it's current state it's a no-go.

**Comment by MrChip53** [comment]
#1145 instead

**Pull request closed without merging**
