### PR TITLE
Use preferences UI for library display preferences

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
_Finishing old branches_

**Changes**
Replaced the DisplayPrefsPopup with preferences UI for a more consistent look and feel. The options in the preferences are now translatable instead of hardcoded strings too.

To apply the new values to the grid fragment I used a check in the onResume function that resets the screen when a value was changed. Ideally we'd use LiveData and change instantly (instead of when preferences close) but I don't want to touch old code too much.
For some reason someone decided to store the values of these preferences as stringified integers, I kept that behavior to prevent the need of migrations.

**Issues**

### CODE REVIEW

**Comment by MrChip53** [comment]
Untitled

This is what I'm getting in the emulator.

**Comment by nielsvanvelzen** [comment]
You somehow managed to get an older version of this branch running in your emulator? Did you perhaps check out my branch earlier?

**Comment by MrChip53** [comment]
Something ridiculous has happened here.

I pulled it using this: `git fetch upstream pull/706/head:niels-prefs-21`

When I try to open my `All Items` section I get a crash and this in my logcat:

```
2021-02-11 20:49:06.062 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.091 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.101 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 7 lines
2021-02-11 20:49:06.106 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.107 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.123 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 9 lines
2021-02-11 20:49:06.126 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.135 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.142 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 4 lines
2021-02-11 20:49:06.143 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.199 5374-5374/org.jellyfin.androidtv.debug D/jellyfin-apiclient: Adding request to queue: https://jellyfin.chip53.xyz:8443/Users/5695012311fb4127af76de46236d3415/Items?ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&recursive=true&Limit=1&IncludeItemTypes=Movie&format=json
2021-02-11 20:49:06.206 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.220 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.228 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.239 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 1 line
2021-02-11 20:49:06.241 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.246 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.252 5374-5374/org.jellyfin.androidtv.debug D/AndroidRuntime: Shutting down VM
2021-02-11 20:49:06.253 5374-5374/org.jellyfin.androidtv.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jellyfin.androidtv.debug, PID: 5374
    java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.GenericGridActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.getCardHeight(StdGridFragment.java:326)
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.onResume(StdGridFragment.java:207)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2601)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at android.app.Activity.performResume(Activity.java:7810)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3981)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7021) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872) 
2021-02-11 20:49:06.255 5374-5374/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a RuntimeException for org.jellyfin.androidtv.debug
    java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.GenericGridActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.getCardHeight(StdGridFragment.java:326)
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.onResume(StdGridFragment.java:207)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2601)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at android.app.Activity.performResume(Activity.java:7810)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3981)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7021) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872) 
2021-02-11 20:49:06.393 5374-5374/org.jellyfin.androidtv.debug I/Process: Sending signal. PID: 5374 SIG: 9
```

I have no idea what the issue is here.

**Comment by MrChip53** [comment]
Something ridiculous has happened here.

I pulled it using this: `git fetch upstream pull/706/head:niels-prefs-21`

When I try to open my `All Items` section I get a crash and this in my logcat:

```
2021-02-11 20:49:06.062 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.091 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.101 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 7 lines
2021-02-11 20:49:06.106 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.107 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.123 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 9 lines
2021-02-11 20:49:06.126 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.135 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.142 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 4 lines
2021-02-11 20:49:06.143 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.TextButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.199 5374-5374/org.jellyfin.androidtv.debug D/jellyfin-apiclient: Adding request to queue: https://localhost:8006/Users/5695012311fb4127af76de46236d3415/Items?ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&recursive=true&Limit=1&IncludeItemTypes=Movie&format=json
2021-02-11 20:49:06.206 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.220 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.228 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.239 5374-5374/org.jellyfin.androidtv.debug I/chatty: uid=10050(org.jellyfin.androidtv.debug) identical 1 line
2021-02-11 20:49:06.241 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.246 5374-5374/org.jellyfin.androidtv.debug E/ThemeUtils: View class org.jellyfin.androidtv.ui.ImageButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-02-11 20:49:06.252 5374-5374/org.jellyfin.androidtv.debug D/AndroidRuntime: Shutting down VM
2021-02-11 20:49:06.253 5374-5374/org.jellyfin.androidtv.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jellyfin.androidtv.debug, PID: 5374
    java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.GenericGridActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.getCardHeight(StdGridFragment.java:326)
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.onResume(StdGridFragment.java:207)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2601)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at android.app.Activity.performResume(Activity.java:7810)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3981)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7021) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872) 
2021-02-11 20:49:06.255 5374-5374/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a RuntimeException for org.jellyfin.androidtv.debug
    java.lang.RuntimeException: Unable to resume activity {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.GenericGridActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.getCardHeight(StdGridFragment.java:326)
        at org.jellyfin.androidtv.ui.browsing.StdGridFragment.onResume(StdGridFragment.java:207)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2601)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at android.app.Activity.performResume(Activity.java:7810)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3981)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4023) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7021) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872) 
2021-02-11 20:49:06.393 5374-5374/org.jellyfin.androidtv.debug I/Process: Sending signal. PID: 5374 SIG: 9
```

I have no idea why this would be happening to me if you can run it fine.

**Comment by nielsvanvelzen** [comment]
I tested with a populated display preferences, if they were not set the values would be null and cause an crash. Fixed now!

**Review by thornbill — APPROVED** [review]
:+1: Looks good!

The only thing I noticed (that is probably not specific to this PR) is the "smart screen" option is displayed for collections, but doesn't actually do anything. Collections always use the "all items" view.

**Comment by nielsvanvelzen** [comment]
I did implement the boolean to hide the smart screen option so I'm quite sure the issue is unrelated to this PR.

**Pull request merged**
