### PR TITLE
Replace bitmaps with vectors

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
**Changes**
  - Removed some unused drawables
  - Moved the moviebg.jpg from nodpi to dpi aware drawables
  - Added vector icons from:
    - item-details-rewrite branch (partially custom made icons)
    - material design icon set (built-in Android Studio feature)
    - materialdesignicons.com
  - Added vector tiles based on the above icons
  - A few renames for consistency

Some of the new icons look slightly different in comparison to the old ones. 

**Notes**

Because a bunch of graphics are cached by Glide you need to stop the app, clear the cache and start it again for the new tiles to show up.

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
image

This is how the new logout/settings tiles look, same background color but different icons.

**Comment by nielsvanvelzen** [comment]
image

Another one (not pushed yet)

**Comment by nielsvanvelzen** [comment]
I don't have Live TV set-up so I was unable to test the live tv screens for any issues. I don't expect anything wrong since everything else works though.

If there's any icon that doesn't make sense please let me know so I can update it.

**Comment by thornbill** [comment]
Here are the icons for Live TV:
Screenshot_1605419499
Live TV Guide, Recorded TV, Schedule, (Recorded) Series

**Review by thornbill — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
Live TV tiles look fine to me!

**Pull request merged**
