### PR TITLE
Show resumable episodes in smart screen for shows

### LINKED ISSUE #2275: Continue Watching doesn't appear in "Smart Screen" for TV/SHOWS Libraries
### Describe the bug

Apparently this only happens for Shows and TV library. 
Movie Libraries are **not affected** and it shows Continue Watching on Smart Screen 

1. Enable Smart screen on TV/Shows
2. Playback an episode and stop halfway
3. Continue Watching **appears** on MAIN SCREEN
4. Click on TV/Shows Smart Screen 
5. No Continue Watching

### Logs

_No response_

### Application version

v0.14.5/v0.15.0-beta.1

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield

### Android version

Latest

### Jellyfin server version

Latest

### PR DESCRIPTION
**Pull request by Clubfan22**
**Changes**
Add another row to the smart screen of show libraries displaying resumable episodes (similar to the implemenation for movies).

**Issues**

Fixes #2275

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]
Normally we don't approve code using the old ApiClient instead of the SDK but in this case it should be easy enough to port once this fragment will be migrated to the SDK.

Thanks for the PR!

**Comment by Clubfan22** [comment]
If you could point me to a sample fragment using the new SDK, I'd gladly port these smart screen fragments in another PR.

**Comment by nielsvanvelzen** [comment]
Migrating the ItemRowAdapter to the SDK is not easy, it means rewriting half of the UI code (everything using the SDK should be written in Kotlin and we don't do Java->Kotlin auto-migrations). So I'm personally just delaying most SDK migrations until rewriting those parts.

**Comment by vortex91** [comment]
Display in home screen sections such as 'Latest Media' and 'Continue Watching optoin currnetly does not get adhered on home screen for android tv but does so on web/ios/android.  will this resolve this issue as well?

**Pull request merged**
