### PR TITLE
Add option to transcode AAC to AC3

### PR DESCRIPTION
**Pull request by MichaelRUSF**
**Changes**

Add an option in the playback preferences menu to transcode AAC to AC3 audio. 

**Issues**
#2867  #2602 #2991

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I'm currently focusing on getting 0.16 out and bugfixes can still be merged but larger changes (especially those with string changes) are unfortunately going to wait for 0.17. This also means it will take some time before I'll review the pull request.

Additionally, my focus with 0.17 is to implement the new playback code for all video playback and completely removing the old implementation which will basically remove all changes from this PR again. The profiles will work quite differently in the rewrite (with fancy auto detection and such) so it won't be easy to port these changes over. Individual toggles for all codecs/formats are planned though.

**Comment by PriceChild** [comment]
I built myself a debug build of this branch and after enabling the new option, I get 5.1 audio, brilliant.

Annoyingly, there's then something up with the video... massive stuttering... seconds between frame updates. I don't see this from the current 0.15 release on Amazon.

I have a 1st-Gen Fire TV. Jellyfin has been great overall but anything aac 5.1 comes out as Stereo.

I also [tried cherry-pick'ing this commit onto the release-0.15.z branch](https://github.com/PriceChild/jellyfin-androidtv/pull/2/commits/0ad3682cf0b61d3bcafff74eb2fd3c4723a78fc2) which had the same result. The jellyfin dashboard reported "The video stream will be repackaged losslessly on the fly before being sent to the device. Only the audio stream will be transcoded." which sounds correct. I don't see any other obvious problems. So not sure if this is because debug builds are different...

I've also tried the 0.16-beta5 and 5.1 sound still goes to stereo, identical to 0.15.

**Comment by MichaelRUSF** [comment]
@PriceChild I downloaded your test build and I didn’t encounter any stuttering. I’m going to assume that it’s a device issue. Gen 1 Fire TV’s had a [bug ](https://github.com/amzn/exoplayer-amazon-port/commit/b249b812d49726fbc269925d1addf0aa57d63bf3)with Dolby Audio which was never fixed in JellyfinATV due to the fact that Exoplayer was [switched ](https://github.com/jellyfin/jellyfin-androidtv/pull/843)from the Amazon fork to the official Google version.

[AC3 ](https://github.com/jellyfin/jellyfin-androidtv/pull/907)streaming was turned off by default in Gen1 devices. Were you able to direct stream multichannel AC3 audio in the official builds with Exoplayer?

**Comment by PriceChild** [comment]
@MichaelRUSF yes. 5.1 ac3 works fine on 0.15.12, the latest Amazon release.

**Comment by wuspy** [comment]
I've been testing this out with my Sony x900h and it works well. My TV/AVR combo also won't play surround from Opus or TrueHD sources so I removed those from allSupportedAudioCodecs as well.

I have had an issue where occasionally playback freezes and I have to restart it. I don't know if that's due to the transcoding, the 0.16 branch, or just a bug in my TV. I'll try applying this patch to 0.15 to see if it still happens there.

Is it possible to only transcode these codecs for multi-channel sources? The majority of my content are TV shows in AAC stereo, which could otherwise be direct played on my TV.

**Comment by wuspy** [comment]
I applied this patch to the 0.15 branch and still occasionally get freezing, so it's nothing to do with changes to the android client. I've only noticed it happening with AAC 7.1 sources though, AAC 5.1 seems to work fine.

This is what I came up with to only transcode surround audio. There might be a better way of doing it but I'm not very familiar with this codebase.

```diff
    private VideoOptions buildExoPlayerOptions(@Nullable Integer forcedSubtitleIndex, org.jellyfin.sdk.model.api.BaseItemDto item, int maxBitrate) {
        VideoOptions internalOptions = new VideoOptions();
        internalOptions.setItemId(item.getId().toString());
        internalOptions.setMediaSources(item.getMediaSources());
        internalOptions.setMaxBitrate(maxBitrate);
+
+       boolean hasSurroundAudio = item.getMediaStreams() != null
+               && item.getMediaStreams().stream().anyMatch(
+                   stream -> stream.getChannels() != null && stream.getChannels() > 2
+               );
+
        if (exoErrorEncountered || (isLiveTv && !directStreamLiveTv))
            internalOptions.setEnableDirectStream(false);
        internalOptions.setMaxAudioChannels(Utils.downMixAudio(mFragment.getContext()) ? 2 : null); //have to downmix at server
        internalOptions.setSubtitleStreamIndex(forcedSubtitleIndex);
        internalOptions.setMediaSourceId(forcedSubtitleIndex != null ? getCurrentMediaSource().getId() : null);
        DeviceProfile internalProfile = new ExoPlayerProfile(
                mFragment.getContext(),
                isLiveTv && !userPreferences.getValue().get(UserPreferences.Companion.getLiveTvDirectPlayEnabled()),
                userPreferences.getValue().get(UserPreferences.Companion.getAc3Enabled()),
-               userPreferences.getValue().get(UserPreferences.Companion.getAacBypassEnabled())
+               hasSurroundAudio && userPreferences.getValue().get(UserPreferences.Companion.getAacBypassEnabled())
        );
        internalOptions.setProfile(internalProfile);
        return internalOptions;
    }
```

**Comment by MichaelRUSF** [comment]
@wuspy  good suggestion for the code. Same issue here with AAC, Opus, & TrueHD only outputting stereo audio on my Sony TV setup.  On my personalized build I have those other two codecs disabled in the exoplayer profile. 
```java
		if (isAC3Enabled && !isAACBYPASSEnabled) add(Codec.Audio.TRUEHD)
		if (isAC3Enabled && !isAACBYPASSEnabled) add(Codec.Audio.OPUS)
``` 
I created a method to get the number of audio channels in the default audio stream as your code checked all streams, which would be an issue for multiple streams with differing amount of audio channels. 

```java
    public Integer getNumberOfChannels () {

        Integer numberOfChannels = 0;

       if (getCurrentMediaSource()!= null &&
                JavaCompat.getDefaultAudioStream(getCurrentMediaSource()) != null &&
                JavaCompat.getDefaultAudioStream(getCurrentMediaSource()).getChannels() !=null) {
            numberOfChannels = JavaCompat.getDefaultAudioStream(getCurrentMediaSource()).getChannels();
        }
        return numberOfChannels;
    }

    @NonNull
    private VideoOptions buildExoPlayerOptions(@Nullable Integer forcedSubtitleIndex, org.jellyfin.sdk.model.api.BaseItemDto item, int maxBitrate) {
        VideoOptions internalOptions = new VideoOptions();
        internalOptions.setItemId(item.getId().toString());
        internalOptions.setMediaSources(item.getMediaSources());
        internalOptions.setMaxBitrate(maxBitrate);

        boolean hasSurroundAudio = getNumberOfChannels() > 2;

        if (exoErrorEncountered || (isLiveTv && !directStreamLiveTv))
            internalOptions.setEnableDirectStream(false);
        internalOptions.setMaxAudioChannels(Utils.downMixAudio(mFragment.getContext()) ? 2 : null); //have to downmix at server
        internalOptions.setSubtitleStreamIndex(forcedSubtitleIndex);
        internalOptions.setMediaSourceId(forcedSubtitleIndex != null ? getCurrentMediaSource().getId() : null);
        DeviceProfile internalProfile = new ExoPlayerProfile(
                mFragment.getContext(),
                isLiveTv && !userPreferences.getValue().get(UserPreferences.Companion.getLiveTvDirectPlayEnabled()),
                userPreferences.getValue().get(UserPreferences.Companion.getAc3Enabled()),
                hasSurroundAudio && userPreferences.getValue().get(UserPreferences.Companion.getAacBypassEnabled())
``` 

Regarding 7.1AAC audio, I didn't have any issues on my end with 7.1 as opposed to 5.1. Both transcoded fine without any playback issues.

**Comment by zkhcohen** [comment]
Just noting that this might have interactions with this bug: https://github.com/jellyfin/jellyfin-androidtv/issues/3227

**Review by piyushtanksale00 — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
Hey @MichaelRUSF, sorry for the wait. It looks like #3110 is similar to this PR but with some more changes so I'm considering closing this one in favor of the other. What do you think?

**Comment by nielsvanvelzen** [comment]
Yeah I didn't expect the delays in #3110 after reviewing it. I can't re-open the PR because the branch was changed since it was closed, if @MichaelRUSF is still interested in this change they can recreate the PR and we'll get that in while we wait for #3110.

**Pull request closed without merging**
