### PR TITLE
Fix 'Play from Here' in video playlists

### LINKED ISSUE #1712: "Shuffle All" and "Play From Here" not working
### Describe the bug

1. Create a playlist (I had to do this on my computer in the web interface, because I see no quick and easy way to turn an entire library into a playlist in the AndroidTV client, nor a way to play an entire library from the AndroidTV client).  I made a music video playlist of all my MV collection, only 261 items.
2. Load the playlist on a TV running the AndroidTV client
3. select "Shuffle All" option, and watch as the player proceeds to begin at the beginning of the playlist and play in order without any shuffling.
4. This is 3-Alternate, select any song in the list and choose "Play From Here" and watch as it proceeds to start again with the first song in the play list in the playlist's original order.

I expect the "Shuffle All" option to select a song at (semi-)random and continue playing all videos in the playlist as random.
I expect "Play From Here" to start playing the playlist in order from the song selected, but instead both options start at the beginning of the list in order.

### Logs

_No response_

### FFmpeg logs

_No response_

### Media info of the file

_No response_

### Application version

0.13.5

### Device information

Onn UHD Streaming Device (Onn 4K TV / askey sti6140d360)

### Android version

Android 10

### Jellyfin server version

10.7.7

### PR DESCRIPTION
**Pull request by kevgrig**
Fixes #1712

Signed-off-by: Kevin G <kevin@myplaceonline.com>

### CODE REVIEW

**Comment by kevgrig** [comment]
@nielsvanvelzen Follow-on to #1910

**Review by nielsvanvelzen — APPROVED** [review]

**Review by mueslimak3r — APPROVED** [review]

**Comment by zkhcohen** [comment]
@kevgrig @nielsvanvelzen 

This commit is causing a playback failure:
```android.view.InflateException: Binary XML file line #41 in org.jellyfin.androidtv.debug:layout/vlc_player_interface: Binary XML file line #41 in org.jellyfin.androidtv.debug:layout/vlc_player_interface: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #41 in org.jellyfin.androidtv.debug:layout/vlc_player_interface: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at org.jellyfin.androidtv.ui.playback.PlaybackController.getCurrentlyPlayingItem(PlaybackController.java:192)
	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.getCurrentlyPlayingItem(VideoPlayerAdapter.java:160)
	at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.getDuration(VideoPlayerAdapter.java:62)
	at androidx.leanback.media.PlaybackBaseControlGlue.getDuration(PlaybackBaseControlGlue.java:458)
	at androidx.leanback.media.PlaybackBaseControlGlue.onMetadataChanged(PlaybackBaseControlGlue.java:572)
	at androidx.leanback.media.PlaybackBaseControlGlue.updateControlsRow(PlaybackBaseControlGlue.java:379)
	at androidx.leanback.media.PlaybackBaseControlGlue.setControlsRow(PlaybackBaseControlGlue.java:341)
	at androidx.leanback.media.PlaybackTransportControlGlue.setControlsRow(PlaybackTransportControlGlue.java:129)
	at androidx.leanback.media.PlaybackBaseControlGlue.onCreateDefaultControlsRow(PlaybackBaseControlGlue.java:280)
	at androidx.leanback.media.PlaybackBaseControlGlue.onAttachedToHost(PlaybackBaseControlGlue.java:227)
	at androidx.leanback.media.PlaybackTransportControlGlue.onAttachedToHost(PlaybackTransportControlGlue.java:171)
	at androidx.leanback.media.PlaybackGlueHost.attachToGlue(PlaybackGlueHost.java:220)
	at androidx.leanback.media.PlaybackGlue.setHost(PlaybackGlue.java:196)
	at org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.onCreate(LeanbackOverlayFragment.java:34)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1720)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at org.jellyfin.androidtv.databinding.VlcPlayerInterfaceBinding.inflate(VlcPlayerInterfaceBinding.java:107)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onCreateView(CustomPlaybackOverlayFragment.java:191)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by nielsvanvelzen** [comment]
Does nothing play for you or just in specific cases? Do you have reproducible steps to trigger the issue?

**Comment by kevgrig** [comment]
Looks like `mCurrentIndex` has been set to `-1` which is invalid, so either the new logic of `mediaManager.getValue().getCurrentMediaPosition()` returned `-1` when initializing the playlist somehow or `mCurrentIndex` was decremented as part of going to a previous playlist item somehow below the first item.

@zkhcohen What did you do leading up to the issue? Did you go to a previous item in the playlist at any point?

@nielsvanvelzen A simple workaround would be to just check that `mCurrentIndex` is `>= 0`. Should I add that or is it better to figure out what's happening (might take some builds with extra logging)?

```diff
index 540b1d27e..2aeefa5f1 100644
--- a/app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
+++ b/app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
@@ -189,7 +189,7 @@ public class PlaybackController implements PlaybackControllerNotifiable {
     }
 
     public BaseItemDto getCurrentlyPlayingItem() {
-        return mItems.size() > mCurrentIndex ? mItems.get(mCurrentIndex) : null;
+        return mCurrentIndex >= 0 && mItems.size() > mCurrentIndex ? mItems.get(mCurrentIndex) : null;
     }
 
     public boolean hasInitializedVideoManager() {
```

**Comment by kevgrig** [comment]
The other possibility is that the commit only called `setCurrentMediaPosition` in the case of a video playlist, so if `CustomPlaybackOverlayFragment`/`PlaybackController` are used in non-video playlists, then `MediaManager.getCurrentMediaPosition` defaults to `-1` so that could also cause the problem, in which case the fix would be to check for `-1` in the `PlaybackController` and default to `0`.

**Comment by kevgrig** [comment]
@nielsvanvelzen Created https://github.com/jellyfin/jellyfin-androidtv/pull/1943

**Comment by zkhcohen** [comment]
@kevgrig I'm away from my computer, but I encountered this issue playing any movie on my server both with VLC and ExoPlayer.

I've never even tried to setup a playlist, so afaik it's unrelated to that specific functionality.

**Comment by kevgrig** [comment]
Ok, that supports the new pull request then as it's probably just taking an uninitialized path

**Pull request merged**
