### PR TITLE
Add header to home screen for focused item

### PR DESCRIPTION
**Pull request by linetrimmer**
**Changes**

- Adds an option to display a header on the home screen that provides details about the item in focus
   - Moves the information shown underneath a card to the header
   - Resizes the cards
   - Displays a logo in place of the title if available
   - Displays a tagline or description for movies/series
   - Aligns the focused item to the leftmost position in the row rather than centering it
- ~~Adds an option to use thumbnails for series and movies on the home screen~~ Removed for future PR
- ~~Uses the preferParentThumb user preference for the Continue Watching row~~ Removed for future PR
- ~~Falls back to a backdrop if a thumbnail is requested but not available~~ Removed for future PR

Note: the app must be reloaded (e.g., go to the switch users page and select your user again) after enabling the header option, otherwise the layout will be off.

**Screenshots**

Screenshot_1625122987

Screenshot_1625275973

Screenshot_1625123131

Screenshot_1625123310

Screenshot_1633480170

### CODE REVIEW

**Comment by themegaphoenix** [comment]
> What do you think about on your point number 1 if we have it randomly scroll through items inside that library of it's a tv, movie or music library?

I am not sure if I am a fan of the "My Media" being horizontal. Ideally I would like as kinda of as a sidebar, so I can switch to a different library really easily. Something like the Jellyfin Web Player:
image
Or the Jellyfin Vue:
image
Channels 4.0:
image

It might be a separate PR for this, but if you could implement this I would be grateful.
Nice work

**Comment by nielsvanvelzen** [comment]
A sidebar is definitely out of scope for this PR. We do have plans for it though.

**Comment by nielsvanvelzen** [comment]
@linetrimmer are you still interested in finishing this pull request? It would be nice to include it in the 0.13 release.

**Comment by nielsvanvelzen** [comment]
Closing this PR as stale. If someone is interested in finishing this they can open a new pull request (make sure to rebase on top of master).

**Pull request closed without merging**
