### PR TITLE
Simplify video player preference

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
**Changes**
- Remove preferred video player preference
- Remove preferred Live TV player preference
- Add "use external player" preference (used for all video related playback)
- Remove "choose player" menu

**Issues**

### CODE REVIEW

**Comment by neopc10** [comment]
Can we have something like "long press play button in episode details to use external player?"

**Comment by nielsvanvelzen** [comment]
No, you either have external player enabled for everything or you don't.

**Review by crobibero — APPROVED** [review]

**Comment by gulabbisht** [comment]
@nielsvanvelzen, is there any way to choose which external player will be used, like vlc?

**Comment by nielsvanvelzen** [comment]
The external player functionality uses the video player configured as default app in the OS.

**Comment by kingp0dd** [comment]
> Can we have something like "long press play button in episode details to use external player?"

I can see a use case for this too. I use exoplayer as default for the resume functionality, but there are videos that do not play with exoplayer, which i have to open with Kodi. So what i do is go to settings to choose "Ask every time" as default video player and then revert the setting again after watching the unplayable video

**Comment by jaum20** [comment]
Why was libvlc option removed?

**Comment by nielsvanvelzen** [comment]
Please stop commenting on pull requests, especially when they're unrelated to your "issue". This pull request did **not** remove LibVLC.

**Comment by sheharyarn** [comment]
Was there a reason for removing "choose player" option? It allowed customizing the playback experience, and I really liked it.

**Comment by miberecz** [comment]
Its getting ridiculous. Every year a very useful feature is deprecated. There were https://github.com/jellyfin/jellyfin-androidtv/issues/2269 which was immensely useful, now this. 
The beauty of this client was that it could handle almost every type of media. If for some reason not, then I still had the choice to circumvent the given issue. Now its less and less. 
Are there any alternative clients for jellyfin on android TV?

**Pull request merged**
