### PR TITLE
Music artist details

### PR DESCRIPTION
**Pull request by nielsvanvelzen**

### CODE REVIEW

**Comment by AndreasGB** [comment]
I've discovered a bug:

Steps:
* Open Music -> Artists -> (some artist) -> Shuffle -> music starts playing
* pause playback from some other screen
* Open an artist -> Shuffle -> no music starts playing 😢

**Comment by nielsvanvelzen** [comment]
When something is playing it will show an popup asking to replace the queue or to append to it. Unfortunately this uses the dirty "currentActivity" property in TvApp.java, this is normally done by BaseActivity. I can add a statement to the DetailsActivity to replace the currentActivity value to fix it but it definitely needs to be properly fixed later.

**Comment by nielsvanvelzen** [comment]
Another way would be to always replace the queue for now and think about a better solution in 0.13

**Comment by AndreasGB** [comment]
I think always replacing is the more expected result, as other apps seem to do this as well (e.g. Spotify, unless the user has manually queued songs... :D)

**Comment by nielsvanvelzen** [comment]
I made the change in #447 so it will find its way to the details branch after the next rebase

**Pull request merged**
