### PR TITLE
Add ACRA for crash reporting

### LINKED ISSUE #193: Crash Reporting for Android TV
## Reasoning

* Providing logs on Android TV devices can be challenging for users (requires Android developer tools `adb`)
* Issues can be challenging to replicate
* Hardware specific issues can be impossible to replicate
* Stack traces can make finding issues much easier

## Concerns

* Relies on a centralized service
* Collects user data
* Uses a third-party service (https://www.tracepot.com)
* Crash reports may contain sensitive or identifiable data
* Will require a privacy policy update for App Stores

## Implementation Details

* Uses a common open-source Android library [ACRA](https://github.com/ACRA/acra).
* ~Crash reporting will be **OPT-IN** and disabled by default in the App Settings~ Due to concerns over crashes on application startup not being captured, the crash reporting dialog will be enabled by default.
* ~After opting-in,~ A dialog prompting the user to submit a crash report will be displayed by default. The user can then choose to send or not send the individual crash.
  * An additional option to always submit crash reports without prompting will be present in App Settings
  * The dialog will clearly indicate that the collected data is submitted to tracepot.com and that crash reporting can be disabled in the App Settings.
* https://github.com/ACRA/acra/wiki/AdvancedUsage#letting-your-users-control-acra
* Reports will be sent to tracepot.com for developer review
* Crash reports are retained for 30 days

## Sample Dialog

screen

## Sample Report

https://gist.github.com/thornbill/e778c0d0dc7b7452d9ceca8fb69aa902

### PR DESCRIPTION
**Pull request by thornbill**
Closes #193

### CODE REVIEW

**Comment by juliashelton** [comment]
Add

**Comment by anthonylavado** [comment]
So far so good 👍

**Comment by thornbill** [comment]
I think this is ready for review now. :tada:

**Comment by AndreasGB** [comment]
Looks good so far, but maybe we should only enable ACRA for release builds.

**Pull request merged**
