### PR TITLE
fix missing server.version

### PR DESCRIPTION
**Pull request by Andy2244**
**Changes**
- fix missing server.version

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I don't see the point of this change. We don't use the server version from the legacy apiclient so we don't need to set it either.

**Comment by Andy2244** [comment]
I use the server version, so i can handle fixes for the 10.8.x servers.

Otherwise whats the point in having a server.version field that's never set?

**Comment by nielsvanvelzen** [comment]
If you need to check a server version you'll need to get the server id from the current session in the SessionRepository and the version from the server in the ServerRepository. The legacy apiclient is deprecated and should not be used for any new code.

**Comment by nielsvanvelzen** [comment]
See also

https://github.com/jellyfin/jellyfin-androidtv/blob/a8dea85a1b27ab993f247e25188ba4cb9d587e56/app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java#L1500-L1517

**Comment by Andy2244** [comment]
So i have to copy&paste all this boilerplate code just to get the server version?
Why is getServerVersionEqualOrGreater() not a static util/api call?

Than getServerInfo() should also be marked deprecated, if we should not use the serverInfo class.

**Comment by nielsvanvelzen** [comment]
I just linked to some example code we temporarily used in 0.13. It's been removed since.

Anyway, closing this PR as we won't be using the old legacy apiclient anymore so this change doesn't do anything.

**Pull request closed without merging**
