### PR TITLE
update to 1.2.58 

### PR DESCRIPTION
**Pull request by grafixeyehero**
need ur review and edit

### CODE REVIEW

**Comment by hawken93** [comment]
Much better. The PR title and description still needs to contain useful information though.

**Comment by hawken93** [comment]
What's the difference between this and #58?

**Comment by grafixeyehero** [comment]
thornbill work is great. this PR for the previous  #56.

**Comment by thornbill** [comment]
Closing as requested https://github.com/jellyfin/jellyfin-androidtv/pull/58#issuecomment-467468990

**Pull request closed without merging**
