### PR TITLE
WIP - need your reviews 

### PR DESCRIPTION
**Pull request by grafixeyehero**
the PR Updated from highattack30 dev branch

### CODE REVIEW

**Comment by hawken93** [comment]
* PR doesn't say what changed
* neither does the commit
* too big for a PR anyway probably
* lots of ugly formatting

This is probably getting closed soon. But I'm curious, what's the source, what's the license status there and is it anything that we should want?

**Comment by hawken93** [comment]
https://github.com/highattack30/Emby.AndroidTv

**Comment by hawken93** [comment]
No promises though, the other people here will probably think about it :)

**Comment by thornbill** [comment]
Great find!

I have opened #58 which is based on the same branch with Jellyfin’s changes merged in which maintains the git history. I am closing this PR since it does not preserve the history.

**Pull request closed without merging**
