### PR TITLE
Improvements to fast forward and rewind

### PR DESCRIPTION
**Pull request by MrChip53**
**Changes**
- Break the seek bar into 10 second segments for more precise seeking
- Add a more "dynamic" fast forward and rewind function

**Todo**
- [x] Put seek segments back to 30 seconds for the seek bar.

**Issues**

### Test and see if the FF/Rewind buttons need to increment faster while holding

I believe between this and the player overlay redesign issue #146 could be considered satisfied.
Also I believe issue #18 should be resolved now also.

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by ManuLinares** [comment]
Seeking in not transcoded files works fine but transcoded files don't, (exoplayer)

Below is a "Horrible seeking fix" that seeking works for transcoded files, but when seeking "seek bar" doesn't update until after seeking. I don't understand the logic to make this work, need a smart pill or some help.

```
--- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java	(revision 234c5319196348fda05e074f0c1ac509b4086236)
+++ app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java	(date 1620277671000)
@@ -871,7 +871,16 @@
         public void run() {
             if (!isPlaying()) return; // in case we completed since this was requested
 
+            if ((mPlaybackMethod == PlayMethod.Transcode && ContainerTypes.MKV.equals(mCurrentStreamInfo.getContainer() ))) {
+                seek(currentSkipPos);
+                currentSkipPos = 0;
+
+            }
             startReportLoop();
+
+            if ((mPlaybackMethod == PlayMethod.Transcode && ContainerTypes.MKV.equals(mCurrentStreamInfo.getContainer() ))) {
+                updateProgress = true; // re-enable true progress updates
+            }
         }
     };
 
@@ -912,9 +921,11 @@
             Timber.d("Duration reported as: %s current pos: %s",mVideoManager.getDuration(), mVideoManager.getCurrentPosition());
             if (currentSkipPos > mVideoManager.getDuration()) currentSkipPos = mVideoManager.getDuration() - 1000;
             mFragment.setCurrentTime(currentSkipPos);
-            seek(currentSkipPos);
-            currentSkipPos = 0;
-            updateProgress = true; // re-enable true progress updates
+            if (!(mPlaybackMethod == PlayMethod.Transcode && ContainerTypes.MKV.equals(mCurrentStreamInfo.getContainer() ))) {
+                seek(currentSkipPos);
+                currentSkipPos = 0;
+                updateProgress = true; // re-enable true progress updates
+            }
             mHandler.postDelayed(skipRunnable, 800);
         }
     }

```

libVLC seeking is shit still...

**Comment by nielsvanvelzen** [comment]
Please open an issue or pull request instead of commenting on old (closed) issues/pull requests/commits

**Comment by ManuLinares** [comment]
But I would like to **revert** this specific commit as it introduced fancy contiguous fast-forward in the detriment of "not working, bad logic". 

> Please open an issue or pull request instead of commenting on old (closed) issues/pull requests/commits

I would never do it if it would impede the software improvement. I only comment on old *issues* when they are wrongly closed so as other devs don't go into the rabbit hole unnecessarily. I'm sorry, if you still consider I need to open a new issue no problem at all. Also thanks to you and every dev working on this project.

**Comment by nielsvanvelzen** [comment]
Yeah we prefer new issues, you can link to the old issues/prs/commits that are relevant but it's easier to discuss in new issues.

**Pull request merged**
