### PR TITLE
Show unfinished episodes in watch next row

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
The watch next row is used by Android TV (leanback) and Google TV to display media content. Until now we've only showed "next up" items (unwatched episodes). This PR adds resumable episodes (episodes not fully watched). I specifically filtered out movies because their posters won't be displayed nicely (they would be resized to 16:9).

I've also marked the "my media" row (shows all libraries) as a default row, this means that users upgrading from 0.11 -> 0.12 will automatically see this row on their home screen.

**Issues**

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
Funny enough the code to show the episode's progress was already written but never activated :p

**Comment by mueslimak3r** [comment]
> I specifically filtered out movies because their posters won't be displayed nicely (they would be resized to 16:9).

Is there a way to make movies look 'good enough' so they can be displayed too? Perhaps by sizing down their image, preserving aspect ratio, and having black bars on the sides. It may be worthwhile trade off for many users for the benefit of having all media available, and not just TV.

Another option could be to use the 'cover' photo instead of the poster. Or to have a settings that allows users to choose to use a resized poster, cover photo, or to hide movies. This could be formatted similar to the "home" user settings on the server, where you can select what media appears.

**Comment by nielsvanvelzen** [comment]
> > I specifically filtered out movies because their posters won't be displayed nicely (they would be resized to 16:9).
> 
> Is there a way to make movies look 'good enough' so they can be displayed too? Perhaps by sizing down their image, preserving aspect ratio, and having black bars on the sides. It may be worthwhile trade off for many users for the benefit of having all media available, and not just TV

Yes this is possible and will be added eventually, but it's out of the scope for this pull request,

**Review by thornbill — APPROVED** [review]
Could you just use the thumb image for movies if one exists?

**Comment by nielsvanvelzen** [comment]
> Could you just use the thumb image for movies if one exists?

Probably but I'd rather add it properly in a separate PR.

**Pull request merged**
