### PR TITLE
Fix screensaver crash when loading an invalid backdrop image

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
**Changes**
- Fix screensaver crash when loading an invalid backdrop image
- Add logging to getRandomLibraryShowcase

**Issues**

```log
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 5150516 markLimit: 5242880)
 call GlideException#logRootCauses(String) for more detail
	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
	at org.jellyfin.androidtv.integration.dream.composable.DreamHostKt$getRandomLibraryShowcase$backdrop$1.invokeSuspend(DreamHost.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e683413, androidx.compose.runtime.BroadcastFrameClock@bee2650, StandaloneCoroutine{Cancelling}@5f2e049, AndroidUiDispatcher@a35ed4e]
Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 5150516 markLimit: 5242880)
 call GlideException#logRootCauses(String) for more detail

```

### CODE REVIEW

**Review by DavidFair — COMMENTED** [review]
I'm still getting app crashes with this branch, including on a clean build

(I've got the image rotation time at 5 seconds to quickly cycle to bad images for testing)

```
ACRA caught a ExecutionException for org.jellyfin.androidtv.debug
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
 call GlideException#logRootCauses(String) for more detail
	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
	at org.jellyfin.androidtv.integration.dream.composable.DreamHostKt$getRandomLibraryShowcase$backdrop$1.invokeSuspend(DreamHost.kt:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@67e852c, androidx.compose.runtime.BroadcastFrameClock@c7a4bf5, StandaloneCoroutine{Cancelling}@7b52d8a, AndroidUiDispatcher@ec09ffb]
Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
 call GlideException#logRootCauses(String) for more detail
 ```

**Comment by nielsvanvelzen** [comment]
Yup I also found that after marking the PR as ready. I believe the issue is that the try-catch should be within the `withContext` that calls the `.get()` function.

**Comment by tukilo** [comment]
> Yup I also found that after marking the PR as ready. I believe the issue is that the try-catch should be within the `withContext` that calls the `.get()` function.

The try-catch didn't fix it either. It still crashes, apparently the exception can't be caught. 
After a bit of debugging I realised that adding a breakpoint to this line fixed the problem. So it seems to be a timing issue somehow. So I added a `.timeout()` of one minute and everything works fine. What is causing this and why does the timeout fix it? I still have no idea.

**Comment by nielsvanvelzen** [comment]
The GlideException was wrapped in a ExecutionException by the Future class. I've moved the try-catch to only run for the Glide call and catch the wrapped exception.

**Review by DavidFair — APPROVED** [review]
I can see the new error appearing in logcat, and it's been running fine for 10+ minutes (where it used to crash in 1-2)

Only nit is it reverts back to the Jellyfin background instead of transparently trying another image for a few seconds, but any crash fix is a great improvement :+1:

**Comment by omerinero** [comment]
> Only nit is it reverts back to the Jellyfin background instead of transparently trying another image for a few seconds, but any crash fix is a great improvement +1

Did you try with the `timeout` ?

**Comment by nielsvanvelzen** [comment]
> Only nit is it reverts back to the Jellyfin background instead of transparently trying another image for a few seconds, but any crash fix is a great improvement 👍

Yeah this is something we need to fix too, I was thinking about some kind of "queue" that preloads the next item when one is already showing. This would also make sure the next item shows after exactly 30 seconds instead of 30 seconds + loading time.

> Did you try with the `timeout` ?

IIRC Glide has a default timeout and this isn't really relevant for this problem.

**Pull request merged**
