### PR TITLE
Fix version selection

### LINKED ISSUE #1521: Multiple versions selector not working
### Describe the bug

1. Open movie with multiple versions
2. select a version not the default
3. play
4. observe that the one selected by default loads instead

this happens with both multi-format movies i have at the moment

Selecting a version in the web player does work correctly, but attempting to cast from the web player to the androidtv app produces the same problem as selecting it through the app.

### Logs

too long for github, attached instead
[logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8239091/logcat.txt)

### FFmpeg logs

```shell
No ffmpeg logs (i guess it was direct-playing) but the jellyfin server logs have lines like this for both the version i chose and the version it's actually playing:

[2022-03-12 22:25:53.290 -08:00] [INF] Profile: "AndroidTV-ExoPlayer", Path: "<REDACTED>", isEligibleForDirectPlay: True, isEligibleForDirectStream: True

When playing from the web player, only lines for the version that was selected are present.
```

### Media info of the file

```shell
The one i wanted to play:

General
Format                                   : Matroska
Format version                           : Version 2
File size                                : 2.81 GiB
Duration                                 : 2 h 1 min
Overall bit rate                         : 3 308 kb/s
Writing application                      : DVDFab 9.2.2.8
Writing library                          : libebml v0.7.8 + libmatroska v0.8.1

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 1 min
Bit rate                                 : 2 794 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.126
Stream size                              : 2.38 GiB (84%)
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 390 MiB (14%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:(01)00:00:00:000
00:00:21.187                             : en:(02)00:00:21:187
00:01:54.616                             : en:(03)00:01:54:616
00:04:53.335                             : en:(04)00:04:53:335
00:07:28.828                             : en:(05)00:07:28:828
00:08:55.217                             : en:(06)00:08:55:217
00:11:21.701                             : en:(07)00:11:21:701
00:15:23.618                             : en:(08)00:15:23:618
00:19:19.862                             : en:(09)00:19:19:862
00:23:13.301                             : en:(10)00:23:13:301
00:25:12.225                             : en:(11)00:25:12:225
00:27:25.196                             : en:(12)00:27:25:196
00:28:52.319                             : en:(13)00:28:52:319
00:32:13.827                             : en:(14)00:32:13:827
00:34:32.637                             : en:(15)00:34:32:637
00:36:33.762                             : en:(16)00:36:33:762
00:38:45.265                             : en:(17)00:38:45:265
00:41:20.893                             : en:(18)00:41:20:893
00:42:10.444                             : en:(19)00:42:10:444
00:43:59.756                             : en:(20)00:43:59:756
00:47:00.743                             : en:(21)00:47:00:743
00:49:06.038                             : en:(22)00:49:06:038
00:50:21.951                             : en:(23)00:50:21:951
00:51:40.699                             : en:(24)00:51:40:699
00:51:48.541                             : en:(25)00:51:48:541
00:54:30.875                             : en:(26)00:54:30:875
00:56:43.846                             : en:(27)00:56:43:846
01:00:41.791                             : en:(28)01:00:41:791
01:03:47.450                             : en:(29)01:03:47:450
01:05:52.946                             : en:(30)01:05:52:946
01:10:03.338                             : en:(31)01:10:03:338
01:11:43.640                             : en:(32)01:11:43:640
01:14:44.795                             : en:(33)01:14:44:795
01:16:40.414                             : en:(34)01:16:40:414
01:19:00.393                             : en:(35)01:19:00:393
01:22:31.277                             : en:(36)01:22:31:277
01:24:33.103                             : en:(37)01:24:33:103
01:27:27.250                             : en:(38)01:27:27:250
01:31:19.189                             : en:(39)01:31:19:189
01:34:10.999                             : en:(40)01:34:10:999
01:35:37.789                             : en:(41)01:35:37:789
01:37:08.182                             : en:(42)01:37:08:182
01:38:55.493                             : en:(43)01:38:55:493
01:40:08.402                             : en:(44)01:40:08:402
01:42:07.892                             : en:(45)01:42:07:892
01:46:48.148                             : en:(46)01:46:48:148
01:52:24.195                             : en:(47)01:52:24:195
01:54:52.648                             : en:(48)01:54:52:648
01:55:34.191                             : en:(49)01:55:34:191
01:57:19.800                             : en:(50)01:57:19:800


And the one that actually played:

General
Format                                   : Matroska
Format version                           : Version 4
File size                                : 71.8 GiB
Duration                                 : 2 h 1 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 84.3 Mb/s
Writing application                      : mkvmerge v65.0.0 ('Too Much') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.3

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 1 min
Bit rate                                 : 77.0 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.387
Stream size                              : 65.4 GiB (91%)
Writing library                          : x265 :[Windows][MSVC 1800][64 bit] 16bpp
Encoding settings                        : wpp / ctu=64 / min-cu-size=8 / max-tu-size=32 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / rdpenalty=0 / no-tskip / no-tskip-fast / no-strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / no-temporal-layers / interlace=0 / keyint=250 / min-keyint=23 / scenecut=40 / rc-lookahead=20 / lookahead-slices=8 / bframes=3 / bframe-bias=0 / b-adapt=2 / ref=5 / limit-refs=3 / no-limit-modes / weightp / no-weightb / aq-mode=1 / qg-size=64 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=3 / psy-rd=2.00 / rdoq-level=0 / psy-rdoq=0.00 / signhide / deblock / sao / no-sao-non-deblock / no-b-pyramid / cutree / no-intra-refresh / rc=2 / pass / bitrate=77000000 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv-maxrate=119250000 / vbv-bufsize=119250000 / ipratio=1.40 / pbratio=1.30
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 2
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 2 h 1 min
Bit rate mode                            : Variable
Bit rate                                 : 1 642 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 1.39 GiB (2%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 2 h 1 min
Bit rate mode                            : Variable
Bit rate                                 : 3 711 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 3.14 GiB (4%)
Language                                 : English
Default                                  : No
Forced                                   : No

Audio #3
ID                                       : 4
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 320 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 277 MiB (0%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #4
ID                                       : 5
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 3 channels
Channel layout                           : L R C
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 333 MiB (0%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #5
ID                                       : 6
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 167 MiB (0%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #6
ID                                       : 7
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 166 MiB (0%)
Language                                 : German
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #7
ID                                       : 8
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 166 MiB (0%)
Language                                 : French
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #8
ID                                       : 9
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 166 MiB (0%)
Language                                 : Spanish
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #9
ID                                       : 10
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 96.0 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 83.2 MiB (0%)
Language                                 : Spanish
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #10
ID                                       : 11
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 166 MiB (0%)
Language                                 : Italian
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #11
ID                                       : 12
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 166 MiB (0%)
Language                                 : Polish
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #12
ID                                       : 13
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 1 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 166 MiB (0%)
Language                                 : Czech
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 14
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 54 min
Bit rate                                 : 69 b/s
Count of elements                        : 1250
Stream size                              : 58.4 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 15
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 52 min
Bit rate                                 : 66 b/s
Count of elements                        : 1162
Stream size                              : 55.2 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 16
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 93 b/s
Count of elements                        : 1176
Stream size                              : 79.1 KiB (0%)
Language                                 : Arabic
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 17
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 78 b/s
Count of elements                        : 1134
Stream size                              : 66.5 KiB (0%)
Language                                 : Bulgarian
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 18
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 42 b/s
Count of elements                        : 1160
Stream size                              : 35.9 KiB (0%)
Language                                 : Czech
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 19
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 46 b/s
Count of elements                        : 986
Stream size                              : 38.8 KiB (0%)
Language                                 : Danish
Default                                  : No
Forced                                   : No

Text #7
ID                                       : 20
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 70 b/s
Count of elements                        : 1177
Stream size                              : 59.2 KiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No

Text #8
ID                                       : 21
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 104 b/s
Count of elements                        : 1168
Stream size                              : 87.8 KiB (0%)
Language                                 : Greek
Default                                  : No
Forced                                   : No

Text #9
ID                                       : 22
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 49 b/s
Count of elements                        : 1164
Stream size                              : 42.0 KiB (0%)
Language                                 : Estonian
Default                                  : No
Forced                                   : No

Text #10
ID                                       : 23
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 93 b/s
Count of elements                        : 1177
Stream size                              : 78.8 KiB (0%)
Language                                 : Persian
Default                                  : No
Forced                                   : No

Text #11
ID                                       : 24
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 57 b/s
Count of elements                        : 1182
Stream size                              : 48.7 KiB (0%)
Language                                 : Finnish
Default                                  : No
Forced                                   : No

Text #12
ID                                       : 25
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 52 s 926 ms
Bit rate                                 : 67 b/s
Count of elements                        : 11
Stream size                              : 444 Bytes (0%)
Language                                 : French
Default                                  : No
Forced                                   : Yes

Text #13
ID                                       : 26
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 58 b/s
Count of elements                        : 1169
Stream size                              : 49.6 KiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No

Text #14
ID                                       : 27
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 70 b/s
Count of elements                        : 1138
Stream size                              : 59.5 KiB (0%)
Language                                 : Hebrew
Default                                  : No
Forced                                   : No

Text #15
ID                                       : 28
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 43 b/s
Count of elements                        : 1139
Stream size                              : 36.6 KiB (0%)
Language                                 : Croatian
Default                                  : No
Forced                                   : No

Text #16
ID                                       : 29
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 47 b/s
Count of elements                        : 1142
Stream size                              : 40.4 KiB (0%)
Language                                 : Hungarian
Default                                  : No
Forced                                   : No

Text #17
ID                                       : 30
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 68 b/s
Count of elements                        : 1182
Stream size                              : 57.4 KiB (0%)
Language                                 : Indonesian
Default                                  : No
Forced                                   : No

Text #18
ID                                       : 31
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 58 b/s
Count of elements                        : 1168
Stream size                              : 49.6 KiB (0%)
Language                                 : Icelandic
Default                                  : No
Forced                                   : No

Text #19
ID                                       : 32
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 52 s 926 ms
Bit rate                                 : 79 b/s
Count of elements                        : 11
Stream size                              : 526 Bytes (0%)
Language                                 : Italian
Default                                  : No
Forced                                   : Yes

Text #20
ID                                       : 33
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 63 b/s
Count of elements                        : 1176
Stream size                              : 53.1 KiB (0%)
Language                                 : Italian
Default                                  : No
Forced                                   : No

Text #21
ID                                       : 34
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 40 b/s
Count of elements                        : 1236
Stream size                              : 33.8 KiB (0%)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Text #22
ID                                       : 35
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 50 b/s
Count of elements                        : 1166
Stream size                              : 42.6 KiB (0%)
Language                                 : Korean
Default                                  : No
Forced                                   : No

Text #23
ID                                       : 36
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 65 b/s
Count of elements                        : 1178
Stream size                              : 54.9 KiB (0%)
Language                                 : Malay
Default                                  : No
Forced                                   : No

Text #24
ID                                       : 37
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 40 b/s
Count of elements                        : 1120
Stream size                              : 33.9 KiB (0%)
Language                                 : Dutch
Default                                  : No
Forced                                   : No

Text #25
ID                                       : 38
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 40 b/s
Count of elements                        : 985
Stream size                              : 33.9 KiB (0%)
Language                                 : Norwegian
Default                                  : No
Forced                                   : No

Text #26
ID                                       : 39
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 62 b/s
Count of elements                        : 1183
Stream size                              : 52.7 KiB (0%)
Language                                 : Polish
Default                                  : No
Forced                                   : No

Text #27
ID                                       : 40
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 57 b/s
Count of elements                        : 1173
Stream size                              : 48.5 KiB (0%)
Language                                 : Portuguese
Default                                  : No
Forced                                   : No

Text #28
ID                                       : 41
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 60 b/s
Count of elements                        : 1176
Stream size                              : 50.6 KiB (0%)
Language                                 : Portuguese
Default                                  : No
Forced                                   : No

Text #29
ID                                       : 42
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 65 b/s
Count of elements                        : 1176
Stream size                              : 55.4 KiB (0%)
Language                                 : Romanian
Default                                  : No
Forced                                   : No

Text #30
ID                                       : 43
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 105 b/s
Count of elements                        : 1180
Stream size                              : 89.3 KiB (0%)
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #31
ID                                       : 44
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 51 b/s
Count of elements                        : 1175
Stream size                              : 43.6 KiB (0%)
Language                                 : Slovenian
Default                                  : No
Forced                                   : No

Text #32
ID                                       : 45
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 63 b/s
Count of elements                        : 1175
Stream size                              : 53.2 KiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #33
ID                                       : 46
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 62 b/s
Count of elements                        : 1175
Stream size                              : 53.0 KiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #34
ID                                       : 47
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 44 b/s
Count of elements                        : 989
Stream size                              : 37.4 KiB (0%)
Language                                 : Swedish
Default                                  : No
Forced                                   : No

Text #35
ID                                       : 48
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 106 b/s
Count of elements                        : 1446
Stream size                              : 89.7 KiB (0%)
Language                                 : Thai
Default                                  : No
Forced                                   : No

Text #36
ID                                       : 49
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 59 b/s
Count of elements                        : 1171
Stream size                              : 50.3 KiB (0%)
Language                                 : Turkish
Default                                  : No
Forced                                   : No

Text #37
ID                                       : 50
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 102 b/s
Count of elements                        : 1183
Stream size                              : 86.1 KiB (0%)
Language                                 : Ukrainian
Default                                  : No
Forced                                   : No

Text #38
ID                                       : 51
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 83 b/s
Count of elements                        : 1180
Stream size                              : 70.6 KiB (0%)
Language                                 : Vietnamese
Default                                  : No
Forced                                   : No

Text #39
ID                                       : 52
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 52 b/s
Count of elements                        : 1179
Stream size                              : 43.9 KiB (0%)
Language                                 : Chinese
Default                                  : No
Forced                                   : No

Text #40
ID                                       : 53
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 38 b/s
Count of elements                        : 1480
Stream size                              : 32.5 KiB (0%)
Language                                 : Chinese
Default                                  : No
Forced                                   : No

Text #41
ID                                       : 54
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 55 min
Bit rate                                 : 38 b/s
Count of elements                        : 1320
Stream size                              : 32.7 KiB (0%)
Language                                 : Chinese
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:
00:00:21.187                             : en:
00:01:54.616                             : en:
00:04:53.335                             : en:
00:07:28.828                             : en:
00:08:55.217                             : en:
00:11:21.701                             : en:
00:15:23.618                             : en:
00:19:19.862                             : en:
00:23:13.301                             : en:
00:25:12.225                             : en:
00:27:25.196                             : en:
00:28:52.319                             : en:
00:32:13.827                             : en:
00:34:32.637                             : en:
00:36:33.762                             : en:
00:38:45.265                             : en:
00:41:20.893                             : en:
00:42:10.444                             : en:
00:43:59.756                             : en:
00:47:00.743                             : en:
00:49:06.038                             : en:
00:50:21.951                             : en:
00:51:40.699                             : en:
00:51:48.541                             : en:
00:54:30.875                             : en:
00:56:43.846                             : en:
01:00:41.791                             : en:
01:03:47.450                             : en:
01:05:52.946                             : en:
01:10:03.338                             : en:
01:11:43.640                             : en:
01:14:44.795                             : en:
01:16:40.414                             : en:
01:19:00.393                             : en:
01:22:31.277                             : en:
01:24:33.103                             : en:
01:27:27.250                             : en:
01:31:19.189                             : en:
01:34:10.999                             : en:
01:35:37.789                             : en:
01:37:08.182                             : en:
01:38:55.493                             : en:
01:40:08.402                             : en:
01:42:07.892                             : en:
01:46:48.148                             : en:
01:52:24.195                             : en:
01:54:52.648                             : en:
01:55:34.191                             : en:
01:57:19.800                             : en:
```

### Application version

v0.13.0-beta.5

### Device information

Nvidia Shield TV Pro 2019

### Android version

9.0.1(33.1.0.283)

### Jellyfin server version

10.7.7

### LINKED ISSUE #3675: Jellyfin for Android TV always plays 1080p instead of 2160p version of film
### Describe the bug

1. Go to https://assets.allsamplefiles.com/mp4/ns/60s/sample-file-full-hd.mp4 and download this film. Rename the file to "whatever - 1080P.mp4".
2. Go to https://www.demolandia.net/downloads.html?id=556436627 and download this film. Rename the file to "whatever - 2160P.ts".
3. Create a folder in a movie library called "whatever". Copy both files in and initiate a library scan.
4. Try to play the 4K version. It never plays. Jellyfin for Android TV always plays the 1080p version.

### Logs

Easy to reproduce.

### FFmpeg logs

```shell
See above.
```

### Media info of the file

_No response_

### Application version

0.16.11

### Device information

TCL

### Android version

No idea

### Jellyfin server version

10.9.6

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
wow this playback code sucks to work with

**Changes**
- Fix version menu not showing current version as selected
- Fix PlaybackController not respecting selected media source

**Issues**

Fixes #3675
Fixes #1521

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Comment by FireByTrial** [comment]
Thank You!

**Comment by silentTeee** [comment]
Thank you for fixing this! For the longest time I thought there was something wrong with how Jellyfin detected my TV's capabilities. Glad it wasn't something that nasty.

**Comment by ThomasPGH** [comment]
Thanks so much. I can't wait to watch 4K films again on the telly.
How long will it take before the app updates itself?

**Comment by nielsvanvelzen** [comment]
It won't be backported to 0.16.z, so it will be in 0.17. I'm working towards a release but I don't have any indication of when it will be ready.

**Pull request merged**
