### PR TITLE
Disable DelayedMessage to prevent crash on login

### PR DESCRIPTION
**Pull request by thornbill**
Temporary workaround for #177

### CODE REVIEW

**Comment by thornbill** [comment]
Just to provide some additional context, this seems to be failing on server discovery because that does not happen on the main ui thread.

**Comment by thornbill** [comment]
I was thinking we could comment it out now and then fix it properly when time allows.

**Comment by garikaib** [comment]
Having the same issue, is there an APK build with this fix applied?

**Comment by thornbill** [comment]
0.10.1 includes this removal. 0.10.2 includes the proper fix from https://github.com/jellyfin/jellyfin-androidtv/pull/189.

**Comment by garikaib** [comment]
Just tested that and for some reason, I cannot add the server. I keep getting a server unavailable error. Looking at the server logs it seems the client is not even attempting to connect.

**Pull request merged**
