### PR TITLE
prefer changing refresh rate without changing resolution

### PR DESCRIPTION
**Pull request by mueslimak3r**
**Changes**
* modes that have the same resolution as the default mode will rank higher than other modes. This will hopefully result in the resolution changing in addition to the refresh rate only if there are no other options.

**Issues**
#1482 

**Notes**
* My display doesn't support the refresh rates needed for this feature. Someone else will need to test it.

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by KyleSanderson** [comment]
@nielsvanvelzen can you revert this? This damages every single user not on a shield as they can't use their TV upscaler anymore.

**Comment by mueslimak3r** [comment]
> This damages every single user not on a shield as they can't use their TV upscaler anymore.

Which shield model do you have?
It's interesting that it broke the upscaler for you but fixed the upscaler for the user who opened #1482

**Comment by KyleSanderson** [comment]
> > This damages every single user not on a shield as they can't use their TV upscaler anymore.
> 
> Which device are you using? It's interesting that it broke the upscaler for you but fixed the upscaler for the user who opened #1482

>Using the refresh rate switch on 4K display when playing 720p/1080p media, the refresh rate is switched to match the video as intended, but the display resolution also switch to 1080p which will block the needed upscale from the nvidia shield.

I do not want to use my device upscaler. My TV is the correct upscaler, as it is for everyone outside of Shield users. The native resolution going to the TV is correct, and should be a "disable" for Shield users as an opt-in only as it's absolutely not desirable behaviour.

**Comment by Dnkhatri** [comment]
I think Kodi implementation of whitelist for resolution and refresh rate matching would probably the best way to go.  

https://github.com/xbmc/xbmc/pull/13274
https://github.com/xbmc/xbmc/pull/16216

**Comment by nielsvanvelzen** [comment]
@KyleSanderson can you open a new issue for your problem? It's easier to track then in the comments of a merged PR. I guess the "easy" solution for now is to have 2 toggles; one for refresh rate switching and one for resolution switching.

**Pull request merged**
