### PR TITLE
Set initial value of currentSession to null to prevent infinite loader on app start

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
**Changes**

I'm not sure what causes this issue but sometimes the app is stuck on the loading screen on start. This PR is a potential fix but since I don't know how to reproduce the issue it's hard to confirm this is the fix.

Running this PR on my device too to see if it fixes the issue.

**Issues**

### CODE REVIEW

**Comment by ManuLinares** [comment]
The "never ending" loading screen happens on my device, when I update the debug apk without an uninstall. Gonna test this.

**Comment by nielsvanvelzen** [comment]
The PR is marked as a draft because I was still testing - it currently does not solve the issue.

**Comment by linetrimmer** [comment]
Not sure if you need logs but this just happened in the emulator on my themes branch (based on master from a few commits ago):

<details><summary>Logs</summary>

```
2021-05-06 00:01:53.546 20434-20478/org.jellyfin.androidtv.debug E/Volley: [789] BasicNetwork.performRequest: Unexpected response code 401 for https://demo.jellyfin.org/stable/Users/a076a5bf-c903-4f37-9f58-89bc6dafc77b?format=json
2021-05-06 00:01:53.551 20434-20434/org.jellyfin.androidtv.debug E/jellyfin-apiclient: VolleyError com.android.volley.AuthFailureError: null
    com.android.volley.AuthFailureError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
2021-05-06 00:01:53.553 20434-20469/org.jellyfin.androidtv.debug E/ApiBinder$updateSession: Unable to retrieve user information or set session capabilities.
    org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.AuthFailureError: 
        at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:25)
        at com.android.volley.Request.deliverError(Request.java:617)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.android.volley.AuthFailureError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

</details>

**Comment by nielsvanvelzen** [comment]
I have some vague ideas of what is wrong. One issue is networking related (no internet connection, unable to connect to server) and that one should be easy to fix. The issue I'm trying to fix first though is different, sometimes when the app is inactive for multiple hours (8+) my television puts it in some kind of state that breaks the SessionsRepository. I'm trying to fix that first.

**Comment by nielsvanvelzen** [comment]
Closing this one for now - will re-open when #853 is merged. the current title/description is incorrect anyway.

**Pull request closed without merging**
