### PR TITLE
Player overlay redesign

### PR DESCRIPTION
**Pull request by Florianisme**
Addresses #146
I think the overall player design might also be reorganized and cleaned up a bit.
 
Redesign will include:

- Reworking of playback progress and seeking
- Redesign of button layout

### CODE REVIEW

**Comment by Florianisme** [comment]
Screenshot_1577981902

Current WIP, I'd like to clean up the button row a bit to make it feel more "Android vanilla" like, don't know how I'm going to archieve that yet

**Comment by nielsvanvelzen** [comment]
If I were to redesign the player I would do the following:
- Remove the poster, it uses a lot of space and I already know what I'm watching
- Remove the release year, I don't really care about that while watching
- Make the controls compacter, it's blocking the video
- "floating" controls (background is now full width, make it smaller) look better
- Add "backward" control. Why can I go forward but not backward?

I think you can get some inspiration from the [leanback documentation](https://developer.android.com/training/tv/playback/transport-controls)

Some other features that would be awesome:
- When controls not visible, using the forward and backward controls on the remote should only show the seekbar, not the entire control view
- Separate the "up next" to it's own activity (I hate how it shows on top of the video so I actually disabled it) - _this one I might do myself in the future_

**Comment by Florianisme** [comment]
@nielsvanvelzen very good points! I didn't want to be too radical with the changes but I think it would be great if @thornbill could give some feedback on our ideas before I start working on them! 

I think that the media player overlay could somewhat behave like the YouTube player for Android TV. Only the main media controls (eg. play, pause, forward, backward) are shown until you press the three dots menu.
We could hide the subtiltle and audio submenus behind that. 
What do you think of that approach?

**Comment by nielsvanvelzen** [comment]
I actually switch subtitles a lot in the player so I'd rather keep them unless we add them to the details activity (so I can set it beforehand).

Would also be nice if we could show the queue and chapters when pressing the "down" button (like Plex does)

Depending on your goals we could keep this PR just a simple "make is look good instead of terrible" and create an issue where we can discuss a new design before implementing it.

**Comment by Florianisme** [comment]
I F*d up my version control, will close this PR and reopen

**Pull request closed without merging**
