### PR TITLE
Feat/play with mpv and resume support

### PR DESCRIPTION
**Pull request by okan35**
**Changes**

So my problem was transcoding and having issues with libvlc and exo player all the time. Also it seems because my android tv box has more than one player, when I click play button with external player preference chose, it always asks to choose a player to play media. Since I was happy with mpv player I just put it automatically under external player and also fixed the resume time, before it did not work, now it starts from the time "resume from" text has.

I am just letting you know if you wish to keep this or just keep fix for mpv player resume. I can adapt the code as you wish. 

If you think it does not solve anything feel free to remove it.
**Issues**

I think it solves this at least to some extent for tracking https://github.com/jellyfin/jellyfin-android/issues/149

### CODE REVIEW

**Comment by okan35** [comment]
It seems something is wrong now it doesn't retrieve position from mpv player.I will make another request after it works.

**Comment by MrChip53** [comment]
Can you mark as draft until done please?

**Comment by okan35** [comment]
Ok, I will.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by nielsvanvelzen** [comment]
@okan35 can we close this pull request?

**Comment by okan35** [comment]
Yes, you can close it.

**Pull request closed without merging**
