### PR TITLE
Add preferences to configure buffering behaviour

### PR DESCRIPTION
**Pull request by rickysixx**
**Changes**

Add 4 new preferences to configure parameters of [`DefaultLoadControl.Builder#setBufferDurationsMs()`](https://developer.android.com/reference/androidx/media3/exoplayer/DefaultLoadControl.Builder?hl=en#setBufferDurationsMs(int,int,int,int))

**Issues**

May be helpful for #2855 (although this PR only configures buffering durations, not the size).

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I don't see a use-case for those preferences. Please explain why we need 4 (!!) new preferences to customize the buffer behavior.

**Comment by rickysixx** [comment]
@nielsvanvelzen Being able to change those parameters allows the user to tweak buffering behaviour to their specific needs, e.g. in case of unstable/not-so-fast internet connection it may be beneficial to exceed the default buffer duration of 50 seconds.

Reducing these durations may be beneficial too, e.g. when listening music lower buffering durations avoid waste of bandwidth in case of frequent skips.

Yes, these are 4 new preferences, but I do not see any problem with that. User is not forced to change these settings if they do not understand what they are doing (or they simply don't care about them) and they still have the library default values for those parameters.

**Comment by nielsvanvelzen** [comment]
Sorry but I don't see the need to fix those problems by introducing additional preferences. Besides, this change doesn't affect the playback code used for music at all.

**Comment by viown** [comment]
I believe we should keep just one preference for controlling the buffer size, in this case minimum buffer (or max buffer depending on how it behaves), but instead of asking the user to specify a duration in seconds, I think we should show selections (e.g Small / Default / Large / Very Large) each with a pre-defined number of seconds or bytes.

As for the other two preferences, I think it just adds unnecessary complexity to the app as I can't think of a scenario where a user would want to change them from the defaults.

**Comment by rickysixx** [comment]
> As for the other two preferences, I think it just adds unnecessary complexity to the app as I can't think of a scenario where a user would want to change them from the defaults.

A user may prefer to wait a little more at the beginning of a movie (i.e. changing `bufferForPlaybackMs` to 20-30 seconds) if this avoids further rebuffering. The same applies to `bufferForPlaybackAfterRebufferMs`.

However, if 4 new preferences are too many, we can keep only one, as suggested by @viown, to control both `minBufferMs` and `maxBufferMs` (I think a duration in seconds is more intuitive for the user than a byte size). A single preference will force the user to have the same value for both of these durations, but I think it's fine (it's what ExoPlayer does already and there are no real advantages in having them separated).

> instead of asking the user to specify a duration in seconds, I think we should show selections (e.g Small / Default / Large / Very Large) each with a pre-defined number of seconds or bytes.

I think a seekbar a user can change freely is more appropriate instead (like it is e.g. for subtitle font size), since every device has different memory capabilities and every user has a different internet speed. Maybe we can come to a compromise here by changing the seekbar increment from the current 1 second to 5/10/30 seconds.

**Comment by nielsvanvelzen** [comment]
If you could update the pull request to use a single preference I will do some additional testing with that and see if it's worth adding to the app. Right now I still don't see a reason to add such a preference though.

**Comment by nielsvanvelzen** [comment]
Hey @rickysixx, are you still interested in finishing this pull request? it's currently waiting for you to address my comment above.

**Comment by rickysixx** [comment]
Hey @nielsvanvelzen, sorry for my late reply.

After using the app for some time I now agree with you that this change is unnecessary, therefore I prefer to focus on more urgent issues.

**Comment by nielsvanvelzen** [comment]
No problem, let's close this for now. We can always revisit it in the future if we do believe it's useful.

**Pull request closed without merging**
