### PR TITLE
Add Koin for dependency injection

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Adds Koin for dependency injection and migrates some global app state to using it instead of referencing TvApp.

**Issues**
N/A

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I've started reviewing but it will take some time since there's a lot of changes.

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
LGTM. I noticed a few places where `get()` was called multiple times instead of using a property for it but it was all in ugly Java classes so I don't care too much about those.

**Comment by thornbill** [comment]
My general approach was to use `inject` if there were more than 1-2 usages of a dependency in a file except for when it was being used in a static public method. That seemed like a reasonable approach to me, but I’m new to Koin lol. 🤷‍♂️

**Comment by nielsvanvelzen** [comment]
I don't see a problem with that, although I prefer using inject via properties everywhere (but I think you did that already in the Kotlin code)

**Review by nielsvanvelzen — APPROVED** [review]

**Pull request merged**
