### PR TITLE
Change source language from en to en-us

### PR DESCRIPTION
**Pull request by theg00s3**
This *should* work

### CODE REVIEW

**Comment by dkanada** [comment]
This should probably just be set in Weblate rather than changed in the source.

**Comment by theg00s3** [comment]
good idea
________________________________

**Comment by dkanada** [comment]
@anthonylavado could you make the change?

**Comment by anthonylavado** [comment]
@dkanada @theg00s3 I actually don't think I can change the name in Weblate. Because no language code is picked up, it is just assuming "English". I could change the definition for that to be English US, but I think it might not break other things.

**Comment by dkanada** [comment]
@anthonylavado so this pull request should get merged before you can set the default in Weblate then?

**Comment by thornbill** [comment]
Based on the Android documentation (https://developer.android.com/guide/topics/resources/localization) we must have the default string values in the default (locale agnostic) location. This is reinforced by the CI build being broken by this change.

**Pull request closed without merging**
