### PR TITLE
Make Debug Builds distinguishable from Release

### PR DESCRIPTION
**Pull request by AndreasGB**

### CODE REVIEW

**Comment by Florianisme** [comment]
Can we also add a new "debug" build flavor? That way I can install the official jellyfin app from the play store besides the debug build on my TV. Now that the debug build even has a new icon, distinguishing them from each other should be no problem?

**Comment by nielsvanvelzen** [comment]
The debug version already uses a separate package-id so installing both at the same time is possible.

**Comment by AndreasGB** [comment]
I'll include your new image soon, @nielsvanvelzen

**Comment by nielsvanvelzen** [comment]
I've checked the Weblate settings to make sure this doesn't screw up something over there and that should be good. It's also possible to [set the name using Gradle](https://stackoverflow.com/a/32562324), might be a preferable option instead of creating an XML file for a single string.

**Comment by AndreasGB** [comment]
So, which of the three options should we pick? I don't have a preference :D

**Comment by nielsvanvelzen** [comment]
I think the option where we add a new string to the strings.xml called "app_name_debug" and use Gradle to set it for debug builds would be great.

**Pull request merged**
